### ISSUE TITLE
How to Use Embedded Broker for Unit Test

### ISSUE THREAD

**Issue by reachmehere89** [amqphub/amqp-10-jms-spring-boot#10]
Can someone share an example on how to use Embedded Broker for Unit Test in spring boot

**Comment by tabish121** [comment]
Refer to the unit tests for the various project examples for some inspiration.
https://github.com/amqphub/amqp-10-jms-spring-boot/blob/master/amqp-10-jms-spring-boot-examples/amqp-10-jms-spring-boot-hello-world/src/test/java/org/amqphub/spring/boot/jms/example/HelloWorldExampleTest.java
