### ISSUE TITLE
Dependency on qpid:1.3.0

### ISSUE THREAD

**Issue by f-aubert** [amqphub/amqp-10-jms-spring-boot#11]
Please update the dependency of qpid to latest version (1.3.0). Thanks a lot for your spring boot starter

**Comment by tabish121** [comment]
Spring Boot requires JDK 8 support so this cannot be upgraded until spring boot moves to JDK 11 only since Qpid JMS 1.0.0+ requires JDK 11

**Comment by tabish121** [comment]
Qpid JMS 0.60.1 was released which is synced with all the fixes from 1.x main branch.
