### ISSUE TITLE
[doubt] - Why using JMS Pool library instead of Spring JMS Caching 

### ISSUE THREAD

**Issue by ricardozanini** [amqphub/amqp-10-jms-spring-boot#6]
Hi!

Recently I've pushed a [new PR to the ActiveMQ Artemis project ](https://github.com/apache/activemq-artemis/pull/2241)  with a sample of how to use AMQP with Spring Boot, using your project as reference. A doubt came up regarding the JMS Pool used. I noted that if the `org.messaginghub.pooled.jms.JmsPoolConnectionFactory` file is presented in the classpath, them you rely on it for pooling. 

The commiters are questioning me why use JMS Pool and not Spring own caching JMS feature. Could you help me? Why you decided to rely on JMS Pool (from messagehub) in this project?

Many thanks for your help! And great job with this project. Much appreciated! ;)

**Comment by tabish121** [comment]
The JMS pool provides configuration capabilities not available in the CachingConnectionFactory and prevent certain not ideal uses like caching consumer which one should really never do.  The code does not preclude you from using the CachingConnectionFactory at all and you can use standard Spring bean trickery to control what is created in you app if you want so if you really need to use CachingConnectionFactory.  The PooledJMS library also provides JMS 2.0 functionality which is useful for those want that.
